apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: myapp
  name: myapp
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: myapp
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
